# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven
        server-id: changl0368
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.CHANGL0368_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.CHANGL0368_TOKEN }}
    - name: Upload SBOM(Cyclonedx)
      uses: actions/upload-artifact@v3
      with:
        name: bom.json
        path: './target/bom.json'

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3.0.2
        with:
          ignore-maven-wrapper: true
  container:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - uses: actions/checkout@v3
      - name: Install pack CLIs including pack and yq
        uses: buildpacks/github-actions/setup-pack@v5.0.0
        with:
          pack-version: '0.29.0'
      - name: Pack build
        run: |
          export CR_PAT=${{ secrets.GHCR_PAT_TOKEN }}
          echo $CR_PAT | docker login ghcr.io -u eggboy --password-stdin
          pack build ghcr.io/jaydemo:0.0.1 --builder paketobuildpacks/builder:base --buildpack paketo-buildpacks/java-azure --env BP_JVM_VERSION=17 --publish

    
